services:
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8070:8080
    networks:
      - listmonk-dev

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    networks:
      - listmonk-dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - listmonk-dev
    environment:
      - POSTGRES_PASSWORD=listmonk-dev
      - POSTGRES_USER=listmonk-dev
      - POSTGRES_DB=listmonk-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-dev-db
        target: /var/lib/postgresql/data

  front:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-frontend"]
    ports:
      - "8080:8080"
    environment:
      - LISTMONK_API_URL=http://backend:9000
    depends_on:
      - db
    volumes:
      - ../:/app
      - listmonk-dev-frontend-modules:/app/frontend/node_modules
      - listmonk-dev-email-builder-modules:/app/frontend/email-builder/node_modules
    networks:
      - listmonk-dev

  backend:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-backend-docker"]
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ../:/app
      - listmonk-dev-frontend-modules:/app/frontend/node_modules
      - listmonk-dev-email-builder-modules:/app/frontend/email-builder/node_modules
      - ${GOPATH:-${HOME}/go}/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - listmonk-dev

  waha:
    image: devlikeapro/waha:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - listmonk-dev
    environment:
      WHATSAPP_API_KEY: ${WAHA_API_KEY:-admin}
      WAHA_PRINT_QR: "true"
      WHATSAPP_HOOK_URL: "http://backend:9000/api/webhooks/waha"
      WHATSAPP_HOOK_EVENTS: "message.ack,message"
    volumes:
      - type: volume
        source: listmonk-dev-waha-sessions
        target: /app/.sessions

volumes:
  listmonk-dev-db:
  listmonk-dev-waha-sessions:
  listmonk-dev-frontend-modules:
  listmonk-dev-email-builder-modules:

networks:
  listmonk-dev:
